### ISSUE TITLE
Implement prototype nodes for each input / output combination

### ISSUE THREAD

**Issue by gab1one** [knime-ip/knip-scijava#23]
There are different possible input / output mappings for Ops, all of which we need to cover with prototype nodes.
- [ ] 0-to-1, for `Command`s that create new data (eg,  a Kernel), see: #24 
- [ ] 1-to-1, for  `Command`s that create one output row for one input row (e.g. filter application), see: #25 
- [ ] 1-to-n, for Ops that create several output rows for one input row (e.g. feature extraction), see: #26

**Comment by gab1one** [comment]
This issue was moved to knime-ip/knip2#18

**Comment by dietzc** [comment]
why did you move this to knip2? this issue is not image processing specific!

**Comment by Squareys** [comment]
@dietzc All but 0-1 have been prototyped in #49, right?

**Comment by dietzc** [comment]
right
